version: '2'

services:
  db:
    image: postgres:10.3-alpine
    ports:
      - 5432:5432
  ci:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    command: sh -c "bundle exec rails webpacker:install && bundle exec rails db:create db:migrate && bundle exec rake test"
