version: '2'

services:
  db:
    image: postgres:10.3-alpine
  ci:
    build: .
    volumes: &web-volumes
      - .:/task_manager
      - ~/.bash_history:/root/.bash_history
    depends_on:
      - db
    environment:
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    command: sh -c "bundle exec rails webpacker:install:react && bundle exec rails db:create db:migrate && bundle exec rake test"
