version: '2'

services:
  db:
    image: postgres:10.3-alpine

  redis:
    image: redis:5.0.9-alpine
  
  sidekiq:
    build: .
    command: bundle exec sidekiq -C /task_manager/config/sidekiq.yml
    environment: *ci-environment
    volumes: *web-volumes
    depends_on:
      - redis
  ci:
    build: .
    volumes: &web-volumes
      - .:/task_manager
      - ~/.bash_history:/root/.bash_history
    depends_on:
      - db
    environment: &ci-environment
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - REDIS_URL=redis://redis

    command: sh -c "bundle exec rails webpacker:install && bundle exec rails db:create db:migrate && bundle exec rake test"
