version: '2'

services:
  db:
    image: postgres:10.3-alpine
  ci:
    build: .
    depends_on:
      - db
    environment:
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    command: sh -c "bundle exec rails webpacker:install && bundle exec rails db:create db:migrate && bundle exec rake test"

  save_lcov:
    depends_on:
      - ci
    command: docker cp web:coverage/lcov/lcov.info coverage/lcov/lcov.info
