version: '2'

services:
  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  ci:
    build: .
    volumes: &web-volumes
      - .:/task_manager
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
    depends_on:
      - db
    environment:
      - COVERAGE
      - RAILS_ENV=test
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    command: sh -c "bundle exec rails webpacker:install && bundle exec rails db:create db:migrate && bundle exec rake test"

volumes:
  bundle_cache:
