name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: tmp

      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
        run: |
          docker-compose --file docker-compose.ci.yml run ci
          sh -c "ls -a tmp"
          sh -c "ls -a"

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: tmp/lcov.info
