name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
      - uses: coverallsapp/github-action@1.1.3
      - name: Coveralls GitHub Action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.xml
        run: docker-compose --file docker-compose.ci.yml run ci
